---

- name: delete the configuration
  blockinfile:
    path: /etc/syslog.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ syslog_config_name }}"
    state: absent
  when: syslog_config_state | default('present') == 'absent'
  notify:
    - syslog restart

- name: create the log file
  file:
    path: "{{ syslog_destination_log_path }}"
    owner: "{{ syslog_destination_user }}"
    group: "{{ syslog_destination_group }}"
    mode: "{{ syslog_destination_mode }}"
  when: syslog_config_state | default('present') == 'present'

- name: add a /dev/log in a chroot -> create parent dir
  file:
    path: "{{ syslog_src_devlog | dirname }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  when: syslog_src_devlog is defined

- name: add a /dev/log in a chroot -> create dev
  lineinfile:
    path: /etc/rc.conf.local
    backrefs: True
    state: present
    regexp: '^(syslogd_flags=(?!.*\b-a {{ syslog_src_devlog }}\b).*)$'
    line: '\1 -a {{ syslog_src_devlog }}'
  when: syslog_src_devlog is defined

- name: create the configuration
  blockinfile:
    path: /etc/syslog.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ syslog_config_name }}"
    block: |
      !!{{ syslog_program_name }}
      {{ syslog_facility }}.{{ syslog_level }}          {{ syslog_destination_log_path }}
      !*
  when: syslog_config_state | default('present') == 'present'
  notify:
    - syslog restart
