---

- name: add the syslog service to init and start the service
  service:
    name: "{% if ansible_facts['distribution'] == 'OpenBSD' %}syslogd{% else %}syslog-ng{% endif %}"
    enabled: True
    state: started
