---

- name: syslog restart
  listen: network restart
  service:
    name: "{% if ansible_facts['distribution'] == 'OpenBSD' %}syslogd{% else %}syslog-ng{% endif %}"
    state: restarted

- name: syslog reload
  listen: chrooted /dev/log
  service:
    name: "{% if ansible_facts['distribution'] == 'OpenBSD' %}syslogd{% else %}syslog-ng{% endif %}"
    state: reloaded
