---

- name: 'syslog_restart_handler'
  service:
    name: "{{ _syslog_service_name }}"
    state: 'restarted'

- name: 'syslog_reload_handler'
  service:
    name: "{{ _syslog_service_name }}"
    state: 'reloaded'
